name: trendy_whatsapp_stickers
description: Complete WhatsApp sticker App using Flutter.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.0.0
  dependencies: null
  esys_flutter_share: ^1.0.2
  firebase_admob: ^0.5.0
  flutter_whatsapp_stickers: null
  font_awesome: ^5.10.1
  splashscreen: ^1.3.5
  url_launcher: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - sticker_packs/1/
    - sticker_packs/2/
    - sticker_packs/3/
    - sticker_packs/4/
    - sticker_packs/5/
    - sticker_packs/6/
    - sticker_packs/7/
    - sticker_packs/sticker_packs.json

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
    - family: Circular
      fonts:
        - asset: fonts/Circular Std Medium.ttf
          weight: 100
